//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompJS_Repo.Centipede.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CentipedeDbEntities : DbContext
    {
        public CentipedeDbEntities()
            : base("name=CentipedeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<decimal>> CreateHighScore(string playerName, Nullable<long> score)
        {
            var playerNameParameter = playerName != null ?
                new ObjectParameter("playerName", playerName) :
                new ObjectParameter("playerName", typeof(string));
    
            var scoreParameter = score.HasValue ?
                new ObjectParameter("score", score) :
                new ObjectParameter("score", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CreateHighScore", playerNameParameter, scoreParameter);
        }
    
        public virtual ObjectResult<RetrieveAllAudio_Result> RetrieveAllAudio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveAllAudio_Result>("RetrieveAllAudio");
        }
    
        public virtual ObjectResult<RetrieveBhvComp_Result> RetrieveAllBhvComps()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveBhvComp_Result>("RetrieveAllBhvComps");
        }
    
        public virtual ObjectResult<RetrieveAllEntityDefinitions_Result> RetrieveAllEntityDefinitions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveAllEntityDefinitions_Result>("RetrieveAllEntityDefinitions");
        }
    
        public virtual ObjectResult<RetrieveGfxComp_Result> RetrieveAllGfxComps()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveGfxComp_Result>("RetrieveAllGfxComps");
        }
    
        public virtual ObjectResult<RetrievePhysComp_Result> RetrieveAllPhysComps()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrievePhysComp_Result>("RetrieveAllPhysComps");
        }
    
        public virtual ObjectResult<RetrieveAnimationFramesForAnimationState_Result> RetrieveAnimationFramesForAnimationState(Nullable<int> animationStateId)
        {
            var animationStateIdParameter = animationStateId.HasValue ?
                new ObjectParameter("animationStateId", animationStateId) :
                new ObjectParameter("animationStateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveAnimationFramesForAnimationState_Result>("RetrieveAnimationFramesForAnimationState", animationStateIdParameter);
        }
    
        public virtual ObjectResult<RetrieveAnimationStatesForGfxComp_Result> RetrieveAnimationStatesForGfxComp(Nullable<int> gfxCompId)
        {
            var gfxCompIdParameter = gfxCompId.HasValue ?
                new ObjectParameter("gfxCompId", gfxCompId) :
                new ObjectParameter("gfxCompId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveAnimationStatesForGfxComp_Result>("RetrieveAnimationStatesForGfxComp", gfxCompIdParameter);
        }
    
        public virtual ObjectResult<RetrieveAudioTypes_Result> RetrieveAudioTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveAudioTypes_Result>("RetrieveAudioTypes");
        }
    
        public virtual ObjectResult<RetrieveBhvComp_Result> RetrieveBhvComp(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveBhvComp_Result>("RetrieveBhvComp", idParameter);
        }

        public virtual ObjectResult<RetrieveBhvComp_Result> RetrieveBhvCompForEntity(Nullable<int> entityId)
        {
            var entityIdParameter = entityId.HasValue ?
                new ObjectParameter("entityId", entityId) :
                new ObjectParameter("entityId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveBhvComp_Result>("RetrieveBhvCompForEntity", entityIdParameter);
        }
    
        public virtual ObjectResult<RetrieveCollisionTypes_Result> RetrieveCollisionTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveCollisionTypes_Result>("RetrieveCollisionTypes");
        }
    
        public virtual ObjectResult<RetrieveEntity_Result> RetrieveEntity(Nullable<int> entityId)
        {
            var entityIdParameter = entityId.HasValue ?
                new ObjectParameter("entityId", entityId) :
                new ObjectParameter("entityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveEntity_Result>("RetrieveEntity", entityIdParameter);
        }
    
        public virtual ObjectResult<RetrieveGfxComp_Result> RetrieveGfxComp(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveGfxComp_Result>("RetrieveGfxComp", idParameter);
        }

        public virtual ObjectResult<RetrieveGfxComp_Result> RetrieveGfxCompForEntity(Nullable<int> entityId)
        {
            var entityIdParameter = entityId.HasValue ?
                new ObjectParameter("entityId", entityId) :
                new ObjectParameter("entityId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveGfxComp_Result>("RetrieveGfxCompForEntity", entityIdParameter);
        }
    
        public virtual ObjectResult<RetrievePhysComp_Result> RetrievePhysComp(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrievePhysComp_Result>("RetrievePhysComp", idParameter);
        }

        public virtual ObjectResult<RetrievePhysComp_Result> RetrievePhysCompForEntity(Nullable<int> entityId)
        {
            var entityIdParameter = entityId.HasValue ?
                new ObjectParameter("entityId", entityId) :
                new ObjectParameter("entityId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrievePhysComp_Result>("RetrievePhysCompForEntity", entityIdParameter);
        }
    
        public virtual ObjectResult<RetrievePhysTypes_Result> RetrievePhysTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrievePhysTypes_Result>("RetrievePhysTypes");
        }
    
        public virtual ObjectResult<RetrieveAllHighScores_Result> RetrieveAllHighScores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveAllHighScores_Result>("RetrieveAllHighScores");
        }
    
        public virtual ObjectResult<RetrieveLevelLayoutsForLevel_Result> RetrieveLevelLayoutsForLevel(Nullable<int> levelId)
        {
            var levelIdParameter = levelId.HasValue ?
                new ObjectParameter("levelId", levelId) :
                new ObjectParameter("levelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveLevelLayoutsForLevel_Result>("RetrieveLevelLayoutsForLevel", levelIdParameter);
        }
    
        public virtual ObjectResult<RetrieveTopHighScores_Result> RetrieveTopHighScores(Nullable<int> count)
        {
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveTopHighScores_Result>("RetrieveTopHighScores", countParameter);
        }
    }
}
